import re
import pytest
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.recardme.com/")
    page.locator("label").filter(has_text="Русский").locator("span").nth(1).click()
    page.get_by_role("button", name="Подтвердить").click()
    page.get_by_role("link", name="Вход").click()
    page.locator("#email").click()
    page.locator("#email").fill("test_prod@gmail.com")
    page.get_by_placeholder("Пароль").click()
    page.get_by_placeholder("Пароль").fill("A200200052!")
    page.get_by_role("button", name="Вход").click()
    page.locator(".p-5 > div > a").click()
    page.get_by_role("button", name="Icon Кешбек карта").click()
    page.get_by_role("button", name="Icon Штампы", exact=True).click()
    page.get_by_role("textbox", name="Название карты").click()
    page.get_by_role("textbox", name="Название карты").fill("штампы")
    page.get_by_role("button", name="Recard Me").click()
    page.get_by_label("", exact=True).nth(2).click()
    page.get_by_label("", exact=True).nth(2).fill("#2090ac")
    page.locator("[id=\"__next\"] div").filter(has_text="Выберите цвета вашей карты.Выберите цвет вашей открытки и текста. После того, ка").nth(2).click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="Pizza").click()
    page.get_by_role("listitem").filter(has_text="Waffles").click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="8", exact=True).click()
    page.get_by_role("button", name="7", exact=True).click()
    page.get_by_role("button", name="6", exact=True).click()
    page.get_by_role("button", name="8", exact=True).click()
    page.get_by_role("button", name="Продолжить").click()
    page.locator(".w-11").first.click()
    page.locator("label > .absolute").first.click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="Empty").first.click()
    page.get_by_role("listitem").filter(has_text="Имя Фамилия").click()
    page.get_by_role("button", name="Empty").first.click()
    page.get_by_text("Подарочные штампы").click()
    page.get_by_role("button", name="Empty").click()
    page.get_by_text("Осталось штампов").click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="Добавить").click()
    page.get_by_text("ЗаголовокОписание или ссылка").click()
    page.get_by_role("textbox", name="Opening hours").click()
    page.get_by_role("textbox", name="Opening hours").fill("ааа")
    page.locator("div").filter(has_text=re.compile(r"^\.\.\.$")).nth(2).click()
    page.get_by_text("Description").click()
    page.get_by_role("textbox", name="Mon-Sun: 10:00 - 20:").click()
    page.get_by_role("textbox", name="Mon-Sun: 10:00 - 20:").fill("вапвп123")
    page.locator("button").filter(has_text=re.compile(r"^Добавить$")).click()
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("button", name="Добавить").click()
    page.get_by_role("textbox", name="скидка 20%").click()
    page.get_by_role("textbox", name="скидка 20%").fill("23")
    page.get_by_role("textbox", name="Введите адрес или место").click()
    page.get_by_role("textbox", name="Введите адрес или место").fill("бишкек")
    page.get_by_text("Бишкек", exact=True).click()
    page.get_by_role("button", name="Add").click()
    page.get_by_role("button", name="Завершить").click()
    page.get_by_role("link", name="Перейти к панели управления").click()
    page.get_by_role("heading", name="Карта штампы").click()